import turtle
screen = turtle.Screen()
screen.setup(width=900, height=700)
turtle.pensize(4)   
turtle.speed(3)
turtle.forward(200)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.pencolor("blue")
turtle.penup()
turtle.left(90)
turtle.forward(50)
turtle.pendown()
turtle.circle(-20)
turtle.penup()
turtle.right(90)
turtle.forward(20)
turtle.dot(10, "blue")
turtle.back(20)
turtle.left(90)
turtle.forward(100)
turtle.pendown()
turtle.circle(-20)
turtle.penup()
turtle.right(90)
turtle.forward(20)
turtle.dot(10, "blue")
turtle.done()
